### ISSUE TITLE
Reading wrong eccentricities 

### ISSUE THREAD

**Issue by TobNilsson** [varenius/ascot#29]
I came across some cases when the eccentricities are not correctly read in. The reason is that ASCOT only reads the values of the eccentricities from column 56 onward in ECCDAT.ecc, thus only getting the first two characters before the decimal for the X/North eccentricity. Hence if this eccentricity is larger than +100 m or lower than -10 m the eccentricity will not be read correctly. This is luckily a very rare case, the only case I noticed is the station PENTICTN after 1996.01.01, where the X eccentricity is -194 m! This only affects a handful of sessions, but for the affected sessions the impact is significant, ASCOT will set the eccentricity to +94 m instead of -194 m, a difference of almost 300 m! 
I will update the code in the file parser.cpp to correct this issue.

**Comment by varenius** [comment]
Good call. Please not that one can refer to issues/commits on the fly. When commiting a change, you can do "fixes X" or you can refer to a commit hash in the ticket. It's nice to tie tickets to code changes. I see you fixed this recently, so for the record I'm adding that this is fixed in 9061c1b7350452c8eb5f6944b7f53233fc20e3d4.
